[profile.default]
solc = "0.8.30"
evm_version = "cancun"
bytecode_hash = "none"
cbor_metadata = false
src = "src"
out = "out"
libs = [ "lib"]
via_ir = true 
optimizer_runs = 1000
fs_permissions = [{ access = "read", path = "./"}]

[profile.test]
via_ir = false
optimizer_runs = 0

[rpc_endpoints]
sepolia = "${SEPOLIA_RPC_URL}"
mainnet = "${MAINNET_RPC_URL}"

[etherscan]
sepolia = { key = "${SEPOLIA_ETHERSCAN_API_KEY}" }
mainnet = { key = "${MAINNET_ETHERSCAN_API_KEY}" }

[fmt]
line_length = 140
single_line_statement_blocks = "single"